apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: postgresql
spec:
  authentication: 
    path: cluster1/team-a-kubernetes
    role: team-a-secret-engine-admin
  type: database
  path: cluster1/team-a
---  
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineConfig
metadata:
  name: postgresql-dev
spec:
  authentication: 
    path: cluster1/team-a-kubernetes
    role: team-a-secret-engine-admin
  pluginName: postgresql-database-plugin
  allowedRoles:
    - read-write
    - read-only
  connectionURL: postgresql://{{username}}:{{password}}@my-postgresql-database.team-a-dev.svc:5432
  rootCredentials:
    secret:
      name: postgresql-admin-password
    passwordKey: postgresql-password
  username: postgres  
  path: cluster1/team-a/postgresql   
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineRole
metadata:
  name: read-only
spec:
  authentication: 
    path: cluster1/team-a-kubernetes
    role: team-a-secret-engine-admin
  path: cluster1/team-a/postgresql
  defaultTTL: 1h
  maxTTL: 24h
  dBName: postgresql-dev
  creationStatements:
    - CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}'; GRANT SELECT ON ALL TABLES IN SCHEMA public TO "{{name}}";  
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineRole
metadata:
  name: read-write
spec:
  authentication: 
    path: cluster1/team-a-kubernetes
    role: team-a-secret-engine-admin
  path: cluster1/team-a/postgresql
  defaultTTL: 1h
  maxTTL: 24h
  dBName: postgresql-dev
  creationStatements:
    - CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}'; GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public TO "{{name}}";  