apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngine
metadata:
  name: postgresql
spec:
  # Add fields here
  serviceAccount: 
    name: vault-admin
  type: database
  configuration:
    plugin_name: postgresql-database-plugin
    connection_url: TODO
    username: vault-admin
    allowed_roles: "*"
    verify_connection: "false"
  configurationFromVaultSecret:
    #get the admin password from this secret
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineRole
metadata:
  name: read-write
spec:
  serviceAccount: 
    name: vault-admin
  secretEngineReference:
    name: postgresql
  configuration:
    creation_statements: | 
      [ "CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}'","GRANT SELECT, UPDATE, INSERT, DELETE ON *.* TO '{{name}}'@'%'" ] 
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineRole
metadata:
  name: read-only
spec:
  # Add fields here
  serviceAccount: 
    name: vault-admin
  secretEngineReference:
    name: postgresql
  configuration:
    creation_statements: | 
      [ "CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}'","GRANT SELECT ON *.* TO '{{name}}'@'%'" ]  