volumePermissions:  
  enabled: true
tls:
  enabled: true
  certificatesSecret: postgresql-tls-secret
  certFilename: "tls.crt"
  certKeyFilename: "tls.key"
existingSecret: postgresql-admin-password
service:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: postgresql-tls-secret
