- op: add
  path: /metadata/annotations/service.alpha.openshift.io~1serving-cert-secret-name
  value: webhook-server-cert
- op: replace
  path: /metadata/name
  value: vault-config-operator-webhook-service
