apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: vault-config-operator
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: vault-config-operator-certs    
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: vault-config-operator
