# permissions for end users to edit databasesecretengineroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databasesecretenginerole-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineroles/status
  verbs:
  - get
