# permissions for end users to view databasesecretengineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databasesecretengineconfig-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineconfigs/status
  verbs:
  - get
