# permissions for end users to edit passwordpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: passwordpolicy-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - passwordpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - passwordpolicies/status
  verbs:
  - get
