# permissions for end users to view passwordpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: passwordpolicy-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - passwordpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - passwordpolicies/status
  verbs:
  - get
