# permissions for end users to view policies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policy-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - policies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - policies/status
  verbs:
  - get
