# permissions for end users to view randomsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: randomsecret-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - randomsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - randomsecrets/status
  verbs:
  - get
