
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineroles/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - policies/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - secretenginemounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - secretenginemounts/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - secretenginemounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - vaultroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - vaultroles/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - vaultroles/status
  verbs:
  - get
  - patch
  - update
