# permissions for end users to edit secretenginemounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretenginemount-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - secretenginemounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - secretenginemounts/status
  verbs:
  - get
