# permissions for end users to view vaultroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultrole-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - vaultroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - vaultroles/status
  verbs:
  - get
