apiVersion: redhatcop.redhat.io/v1alpha1
kind: AzureSecretEngineConfig
metadata:
  labels:
    app.kubernetes.io/name: azuresecretengineconfig
    app.kubernetes.io/instance: azuresecretengineconfig-sample
    app.kubernetes.io/part-of: vault-config-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vault-config-operator
  name: azuresecretengineconfig-sample
spec:
  # TODO(user): Add fields here
