apiVersion: redhatcop.redhat.io/v1alpha1
kind: AzureSecretEngineRole
metadata:
  labels:
    app.kubernetes.io/name: azuresecretenginerole
    app.kubernetes.io/instance: azuresecretenginerole-sample
    app.kubernetes.io/part-of: vault-config-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vault-config-operator
  name: azuresecretenginerole-sample
spec:
  # TODO(user): Add fields here
