apiVersion: redhatcop.redhat.io/v1alpha1
kind: AzureAuthEngineRole
metadata:
  labels:
    app.kubernetes.io/name: azureauthenginerole
    app.kubernetes.io/instance: azureauthenginerole-sample
    app.kubernetes.io/part-of: vault-config-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vault-config-operator
  name: azureauthenginerole-sample
spec:
  # TODO(user): Add fields here
