name: Build and Publish Helm Chart

on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.15.0'

    - name: Determine version
      id: version
      run: |
        # Extract version from release tag (remove 'v' prefix if present)
        VERSION="${{ github.event.release.tag_name }}"
        VERSION="${VERSION#v}"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      run: |
        IMAGE_TAG="${{ env.REGISTRY }}/${{ github.repository_owner }}/vault-config-operator:${{ steps.version.outputs.version }}"
        make docker-build IMG="${IMAGE_TAG}"
        docker push "${IMAGE_TAG}"

    - name: Build Helm chart
      run: |
        IMAGE_TAG="${{ env.REGISTRY }}/${{ github.repository_owner }}/vault-config-operator:${{ steps.version.outputs.version }}"
        make helmchart VERSION="${{ steps.version.outputs.version }}" IMG="${IMAGE_TAG}"

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Package Helm chart
      run: |
        mkdir -p ./helm-repo
        helm package ./charts/vault-config-operator/ -d ./helm-repo/
        helm repo index ./helm-repo/ --url "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./helm-repo

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Upload Release Assets
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.release.tag_name }}
        artifacts: "./helm-repo/vault-config-operator-${{ steps.version.outputs.version }}.tgz"
        allowUpdates: true
        updateOnlyUnreleased: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Summary
      run: |
        echo "## 🎉 Build and Publish Completed!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Version:** ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Docker Image:** ${{ env.REGISTRY }}/${{ github.repository_owner }}/vault-config-operator:${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Helm Repository:** https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Installation" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "helm repo add vault-config-operator https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}" >> $GITHUB_STEP_SUMMARY
        echo "helm install vault-config-operator vault-config-operator/vault-config-operator --version ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
