name: pull request
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  shared-operator-workflow:
    name: shared-operator-workflow
    uses: redhat-cop/github-workflows-operators/.github/workflows/pr-operator.yml@52256432f2728694ca1c185d16c366f34a30ce4d # v1.0.7
    with: 
      RUN_UNIT_TESTS: true
      RUN_INTEGRATION_TESTS: true
      RUN_HELMCHART_TEST: true
      GO_VERSION: ~1.21
      OPERATOR_SDK_VERSION: v1.25.3
